namespace Tea2D.SourceGenerators.ComponentFilters.ComponentsTuple
{
    public sealed class ComponentsTuplesContentBuilder
    {
        private readonly SourceCodeBuilder _builder;

        public ComponentsTuplesContentBuilder()
        {
            _builder = new SourceCodeBuilder();
            _builder.AppendLine("// <auto-generated/>");
            _builder.AppendLine("namespace Tea2D.Ecs.ComponentFilters;");

            _builder.AppendLine();
        }

        public void Add(string[] genericParameters)
        {
            ComponentsTupleStructBuilder.Build(_builder, genericParameters);
            _builder.AppendLine();
        }

        public string GetContent()
        {
            return _builder.ToString();
        }
    }
}