volumes:
  artifacts:
    targetFolder: /artifacts
    folderToOutput: ./artifacts
    readOnly: false
  imports:
    targetFolder: /imports
    folderToImport: ./imports
    readOnly: false
  source:
    targetFolder: /src
    folderToImport: ./src
    readOnly: false
activities:
  cloc:
    image: aldanial/cloc
    command:
      - --by-file
      - --report-file=/artifacts/stat.cloc.json
      - --json
      - /src
  cloc-converter:
    image: godeltech/codereview.file-converter
    command:
      - cloc
      - --output
      - /artifacts/stat-converted.cloc.json
      - --file
      - /artifacts/stat.cloc.json
      - --prefix
      - /src/
  cloc-evaluator:
    image: godeltech/codereview.evaluator
    command:
      - import-file-details
      - --details
      - /artifacts/stat-converted.cloc.json
      - --output
      - /artifacts/roslyn-issues.db
  roslyn:
    image: godeltech/codereview.analyzers.roslyn
    timeout: "1:00:00"
    environment:
      SOLUTION_FILE_PATH: /src/{SOLUTION_FILE_PATH}
  roslyn-converter:
    image: godeltech/codereview.file-converter
    command:
      - roslyn
      - --output
      - /artifacts/rolsyn-result.zip
      - --folder
      - /artifacts
      - --src
      - /imports/
      - --mask
      - '*.roslyn.json'
  roslyn-evaluator:
    image: godeltech/codereview.evaluator
    command:
      - import-issues
      - --output
      - /artifacts/roslyn-issues.db
      - --issues
      - /artifacts/rolsyn-result.zip
  roslyn-evaluator-evaluate:
    image: godeltech/codereview.evaluator
    command:
      - evaluate
      - --db
      - /artifacts/roslyn-issues.db
      - --manifest
      - /imports/evaluator-manifest.yaml
      - --output
      - /artifacts/result.json
  report-template-renderer-liquid:
    image: godeltech/codereview.template-renderer
    command:
      - liquid
      - --template
      - /imports/report.html.liquid
      - --output
      - /artifacts/report.html
      - --data
      - /artifacts/result.json