namespace Tea2D.Vulkan.Generator;

public sealed class SourceFileWriter : ISourceWriter
{
    private readonly StreamWriter _fileWriter;

    public SourceFileWriter(string filePath, string @namespace, params string[] includes)
    {
        _fileWriter = new StreamWriter(filePath);

        WriteLine("// ============================================================================ ");
        WriteLine("// This file is generated by Tea2D.Sfml.Generator tool. ");
        WriteLine("// ============================================================================ ");
        WriteLine();

        foreach (var include in includes)
        {
            Write("using ");
            Write(include);
            WriteLine(";");
        }

        if (includes.Any())
            WriteLine();
        
        Write("namespace ");
        Write(@namespace);
        WriteLine(';');
    }
    
    public IDisposable BeginBlock(string prefix)
    {
        throw new NotImplementedException();
    }

    public void Write(char symbol) => _fileWriter.Write(symbol);

    public void Write(string str) => _fileWriter.Write(str);

    public void WriteLine(char symbol) => _fileWriter.WriteLine(symbol);

    public void WriteLine(string str) => _fileWriter.WriteLine(str);

    public void WriteLine() => _fileWriter.WriteLine();

    public void Dispose()
    {
        _fileWriter.Dispose();
    }
}