namespace Tea2D.SourceGenerators.ComponentFilters.ComponentsFilter
{
    //TODO: refactor this in near future

    public sealed class ComponentFiltersContentBuilder
    {
        private readonly SourceCodeBuilder _builder;

        public ComponentFiltersContentBuilder()
        {
            _builder = new SourceCodeBuilder();
            _builder.AppendLine("// <auto-generated/>");
            _builder.AppendLine("namespace Tea2D.Ecs.ComponentFilters;");
            _builder.AppendLine();
        }

        public void AppendFilter(params string[] templatesParams)
        {
            ComponentFiltersClassBuilder.Build(_builder, templatesParams);
        }

        public string GetContent()
        {
            return _builder.ToString();
        }
    }
}